---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jacky.
--- DateTime: 2025/1/17 13:24
---

-- 传入的参数 - 优惠券 id、用户 id 与订单 id
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

-- 库存 key 与订单 key
local stockKey = "seckill:stock:" .. voucherId
local orderKey = "seckill:order:" .. voucherId

-- 脚本业务
-- 判断库存是否充足
if(tonumber(redis.call('get', stockKey)) <= 0) then
    -- 库存不足，返回 1
    return 1
end
-- 判断用户是否下单
if(redis.call('sismember', orderKey, userId) == 1) then
    -- 存在则说明是重复下单，返回2
    return 2
end
-- 扣库存，保存用户
redis.call('incrby', stockKey, -1)
redis.call('sadd', orderKey, userId)
-- 发送消息到消息队列中
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)

return 0
