---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Jacky.
--- DateTime: 2025/1/17 13:24
---

-- 优惠券 id 与用户 id 为传入的参数
local voucherId = ARGV[1]
local userId = ARGV[2]

-- 库存 key 与订单 key
local stockKey = "seckill:stock:" .. voucherId
local orderKey = "seckill:order:" .. voucherId

-- 脚本业务
-- 判断库存是否充足
if(tonumber(redis.call('get', stockKey)) <= 0) then
    -- 库存不足，返回 1
    return 1
end
-- 判断用户是否下单
if(redis.call('sismember', orderKey, userId) == 1) then
    -- 存在则说明是重复下单，返回2
    return 2
end
-- 扣库存，保存用户
redis.call('incrby', stockKey, -1)
redis.call('sadd', orderKey, userId)

return 0
